/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;

import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testAppHasAnError(){
        String[] test = new String[]{"/src/main/resources/test.js"};

        App obj = new App();
        int errorCount =0;

       //            expected,        actual
        assertEquals(obj.main(test), errorCount);
    }
    @Test
    public void testHasNoError(){
        String[] test = new String[]{"/src/main/resources/hasAnError.js"};

        App obj = new App();
        int errorCount =0;

        //            expected,        actual
        assertEquals(obj.main(test), errorCount);

    }
    @Test
    public void testHasFewErr(){
        String[] test = new String[]{"/src/main/resources/hasFewErr.js"};

        App obj = new App();
        int errorCount =3;

        //            expected,        actual
        assertEquals(obj.main(test), errorCount);
    }
    @Test
    public void testHasManyErr(){
        String[] test = new String[]{"/src/main/resources/hasManyErr.js"};

        App obj = new App();
        int errorCount =3;

        //            expected,        actual
        assertEquals(obj.main(test), errorCount);
    }
    @Test
    public void testIsEmpty(){
        String[] test = new String[]{"/src/main/resources/isEmpty.js"};

        App obj = new App();
        int errorCount =0;

        //            expected,        actual
        assertEquals(obj.main(test), errorCount);
    }


}
