/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {

    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        int expectedOutput = 5;
        assertEquals("someLibraryMethod should return 'true'", expectedOutput, classUnderTest.roll(5).length);
    }

    @Test
    public void testRoll() {
        Library classUnderTest = new Library();
        int[] testArray = classUnderTest.roll(4);
        assertTrue("checkOutput should return 'true'", testArray[0] >=1 && testArray[0] <=6);
    }

}