/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {
    //https://stackoverflow.com/questions/1200621/how-do-i-declare-and-initialize-an-array-in-java
    public static int[] roll(int n){
        // make an array
        int[] myIntArray = new int[n];;
        // inside a for loop
        for(int i=0; i<n;i++) {
            //https://www.mkyong.com/java/java-generate-random-integers-in-a-range/
            double randomNum = (Math.random() * ((6 - 1) + 1)) + 1;
            // random number
            // put in an array
            myIntArray[i] = (int) randomNum;
            // return an array
        }
        return myIntArray;
    }
}
